export const CRYPTO_COINS_LIST = [
  {
    id: 'bitcoin',
    name: 'Bitcoin',
    symbol: 'btc',
    market_cap_rank: 1,
    large: 'https://assets.coingecko.com/coins/images/1/large/bitcoin.png?1696501400',
  },
  {
    id: 'ethereum',
    name: 'Ethereum',
    symbol: 'eth',
    market_cap_rank: 2,
    large: 'https://assets.coingecko.com/coins/images/279/large/ethereum.png?1696501628',
  },
  {
    id: 'tether',
    name: 'Tether',
    symbol: 'usdt',
    market_cap_rank: 3,
    large: 'https://assets.coingecko.com/coins/images/325/large/Tether.png?1696501661',
  },
  {
    id: 'binancecoin',
    name: 'BNB',
    symbol: 'bnb',
    market_cap_rank: 4,
    large: 'https://assets.coingecko.com/coins/images/825/large/bnb-icon2_2x.png?1696501970',
  },
  {
    id: 'solana',
    name: 'Solana',
    symbol: 'sol',
    market_cap_rank: 5,
    large: 'https://assets.coingecko.com/coins/images/4128/large/solana.png?1696504756',
  },
  {
    id: 'ripple',
    name: 'XRP',
    symbol: 'xrp',
    market_cap_rank: 6,
    large: 'https://assets.coingecko.com/coins/images/44/large/xrp-symbol-white-128.png?1696501442',
  },
  {
    id: 'usd-coin',
    name: 'USDC',
    symbol: 'usdc',
    market_cap_rank: 7,
    large: 'https://assets.coingecko.com/coins/images/6319/large/usdc.png?1696506694',
  },
  {
    id: 'staked-ether',
    name: 'Lido Staked Ether',
    symbol: 'steth',
    market_cap_rank: 8,
    large: 'https://assets.coingecko.com/coins/images/13442/large/steth_logo.png?1696513206',
  },
  {
    id: 'cardano',
    name: 'Cardano',
    symbol: 'ada',
    market_cap_rank: 9,
    large: 'https://assets.coingecko.com/coins/images/975/large/cardano.png?1696502090',
  },
  {
    id: 'avalanche-2',
    name: 'Avalanche',
    symbol: 'avax',
    market_cap_rank: 10,
    large: 'https://assets.coingecko.com/coins/images/12559/large/Avalanche_Circle_RedWhite_Trans.png?1696512369',
  },
  {
    id: 'dogecoin',
    name: 'Dogecoin',
    symbol: 'doge',
    market_cap_rank: 11,
    large: 'https://assets.coingecko.com/coins/images/5/large/dogecoin.png?1696501409',
  },
  {
    id: 'tron',
    name: 'TRON',
    symbol: 'trx',
    market_cap_rank: 12,
    large: 'https://assets.coingecko.com/coins/images/1094/large/tron-logo.png?1696502193',
  },
  {
    id: 'polkadot',
    name: 'Polkadot',
    symbol: 'dot',
    market_cap_rank: 13,
    large: 'https://assets.coingecko.com/coins/images/12171/large/polkadot.png?1696512008',
  },
  {
    id: 'chainlink',
    name: 'Chainlink',
    symbol: 'link',
    market_cap_rank: 14,
    large: 'https://assets.coingecko.com/coins/images/877/large/chainlink-new-logo.png?1696502009',
  },
  {
    id: 'the-open-network',
    name: 'Toncoin',
    symbol: 'ton',
    market_cap_rank: 15,
    large: 'https://assets.coingecko.com/coins/images/17980/large/ton_symbol.png?1696517498',
  },
  {
    id: 'matic-network',
    name: 'Polygon',
    symbol: 'matic',
    market_cap_rank: 16,
    large: 'https://assets.coingecko.com/coins/images/4713/large/polygon.png?1698233745',
  },
  {
    id: 'wrapped-bitcoin',
    name: 'Wrapped Bitcoin',
    symbol: 'wbtc',
    market_cap_rank: 17,
    large: 'https://assets.coingecko.com/coins/images/7598/large/wrapped_bitcoin_wbtc.png?1696507857',
  },
  {
    id: 'shiba-inu',
    name: 'Shiba Inu',
    symbol: 'shib',
    market_cap_rank: 18,
    large: 'https://assets.coingecko.com/coins/images/11939/large/shiba.png?1696511800',
  },
  {
    id: 'dai',
    name: 'Dai',
    symbol: 'dai',
    market_cap_rank: 19,
    large: 'https://assets.coingecko.com/coins/images/9956/large/Badge_Dai.png?1696509996',
  },
  {
    id: 'internet-computer',
    name: 'Internet Computer',
    symbol: 'icp',
    market_cap_rank: 20,
    large: 'https://assets.coingecko.com/coins/images/14495/large/Internet_Computer_logo.png?1696514180',
  },
  {
    id: 'litecoin',
    name: 'Litecoin',
    symbol: 'ltc',
    market_cap_rank: 21,
    large: 'https://assets.coingecko.com/coins/images/2/large/litecoin.png?1696501400',
  },
  {
    id: 'uniswap',
    name: 'Uniswap',
    symbol: 'uni',
    market_cap_rank: 22,
    large: 'https://assets.coingecko.com/coins/images/12504/large/uni.jpg?1696512319',
  },
  {
    id: 'bitcoin-cash',
    name: 'Bitcoin Cash',
    symbol: 'bch',
    market_cap_rank: 23,
    large: 'https://assets.coingecko.com/coins/images/780/large/bitcoin-cash-circle.png?1696501932',
  },
  {
    id: 'cosmos',
    name: 'Cosmos Hub',
    symbol: 'atom',
    market_cap_rank: 24,
    large: 'https://assets.coingecko.com/coins/images/1481/large/cosmos_hub.png?1696502525',
  },
  {
    id: 'leo-token',
    name: 'LEO Token',
    symbol: 'leo',
    market_cap_rank: 25,
    large: 'https://assets.coingecko.com/coins/images/8418/large/leo-token.png?1696508607',
  },
  {
    id: 'ethereum-classic',
    name: 'Ethereum Classic',
    symbol: 'etc',
    market_cap_rank: 26,
    large: 'https://assets.coingecko.com/coins/images/453/large/ethereum-classic-logo.png?1696501717',
  },
  {
    id: 'stellar',
    name: 'Stellar',
    symbol: 'xlm',
    market_cap_rank: 27,
    large: 'https://assets.coingecko.com/coins/images/100/large/Stellar_symbol_black_RGB.png?1696501482',
  },
  {
    id: 'okb',
    name: 'OKB',
    symbol: 'okb',
    market_cap_rank: 28,
    large: 'https://assets.coingecko.com/coins/images/4463/large/WeChat_Image_20220118095654.png?1696505053',
  },
  {
    id: 'optimism',
    name: 'Optimism',
    symbol: 'op',
    market_cap_rank: 29,
    large: 'https://assets.coingecko.com/coins/images/25244/large/Optimism.png?1696524385',
  },
  {
    id: 'near',
    name: 'NEAR Protocol',
    symbol: 'near',
    market_cap_rank: 30,
    large: 'https://assets.coingecko.com/coins/images/10365/large/near.jpg?1696510367',
  },
];
